postgres.connections.used-percent:
  expr: 'sum(pg_stat_database_numbackends) / max(pg_settings_max_connections) * 100'

postgres.activity.active-sessions:
  expr: 'sum(pg_stat_activity_count{state="active"})'

postgres.locks.by-mode:
  expr: 'sum by (mode) (pg_locks_count)'

postgres.xact.commit-rate:
  expr: 'rate(pg_stat_database_xact_commit[$__rate_interval])'

postgres.xact.rollback-rate:
  expr: 'rate(pg_stat_database_xact_rollback[$__rate_interval])'

postgres.table.seq-scan-by-table:
  expr: 'sum by (relname) (rate(pg_stat_user_tables_seq_scan{relname=~"$table"}[$__rate_interval]))'

postgres.table.idx-scan-by-table:
  expr: 'sum by (relname) (rate(pg_stat_user_tables_idx_scan{relname=~"$table"}[$__rate_interval]))'

postgres.table.seq-tuples-read-rate-by-table:
  expr: 'sum by (relname) (rate(pg_stat_user_tables_seq_tup_read{relname=~"$table"}[$__rate_interval]))'

postgres.table.idx-tuples-fetch-rate-by-table:
  expr: 'sum by (relname) (rate(pg_stat_user_tables_idx_tup_fetch{relname=~"$table"}[$__rate_interval]))'
