services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./postgres/init/01_monitoring.sql:/docker-entrypoint-initdb.d/01_monitoring.sql
      - ./postgres/init/02_schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d reservation"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://prometheus:prometheus@postgres:5432/reservation?sslmode=disable" # prometheus 유저로 reservation db 접근
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver" # k6 Remote Write 수신 활성화
    extra_hosts:
      - "host.docker.internal:host-gateway" # 로컬 Spring Boot 서버 접근용
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts # 로컬 scripts 폴더를 컨테이너에 마운트
    depends_on:
      - prometheus
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    # k6 로드 테스트를 실행하려면 아래 커맨드를 덮어쓰거나 프로필 모드로 실행하세요.
    command: run --out experimental-prometheus-rw /scripts/simple_test.js
    extra_hosts:
      - "host.docker.internal:host-gateway" # 로컬 Spring Boot 서버 접근용
    profiles:
      - test # `docker compose --profile test up k6` 으로 실행 가능

volumes:
  grafana-storage:
