spring:
  application:
    name: concurrency
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-init-sql: "SET lock_timeout = '1s'"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      # javax.persistence.lock.timeout: 1000 # 1초 (단위: ms) (postgresql 기준
      jakarta.persistence.lock.timeout: 1000
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
