PHASE ?= 02-no-lock-baseline
GRAFANA_PHASE ?= phase-02
SCENARIO ?= no-lock
PRESET ?= baseline
K6_PRESET ?= $(PRESET)
GRAFANA_PRESET ?= $(PRESET)
MODE ?= prometheus
POOL ?= default
POOL_SIZE ?= 10
LOCK_TIMEOUT ?= 0
PROFILE ?= local
PORT ?= 8080
CONDITION ?= baseline
TAIL ?= 120
PYTHON ?= python.exe
DASHBOARD ?= overview
RUN_WINDOW ?= auto
STRATEGY ?= pessimistic-lock
TABLE ?=
URI ?=
PARTS_DIR ?= docs/evidence/$(PHASE)/grafana/parts
INPUT ?=
OUTPUT ?=
EXPERIMENT ?=
SQL_CONDITION ?= $(CONDITION)
SQL_OUTPUT ?= docs/evidence/$(PHASE)/$(EXPERIMENT)/$(SQL_CONDITION)/sql/consistency.txt
