.PHONY: help

help:
	@echo "Spring Concurrency Lab command interface"
	@echo
	@echo "Common targets:"
	@echo "  make env-check"
	@echo "      필수 도구와 로컬 실행 환경을 확인한다."
	@echo "  make db-start PROFILE=local"
	@echo "      PostgreSQL, postgres_exporter, Prometheus, Grafana를 실행한다."
	@echo "  make server-start PROFILE=local PORT=8080"
	@echo "      Spring Boot 애플리케이션을 실행한다."
	@echo "  make server-start POOL_SIZE=10 LOCK_TIMEOUT=500"
	@echo "      HikariCP pool size와 PostgreSQL lock_timeout(ms)을 지정해 실행한다."
	@echo "  make k6-run K6_PRESET=baseline MODE=prometheus"
	@echo "      k6 preset을 실행한다. PRESET은 기존 호환용이고 K6_PRESET이 실제 파일명을 의미한다."
	@echo "  make k6-evidence PHASE=02-no-lock-baseline K6_PRESET=baseline MODE=prometheus CONDITION=baseline"
	@echo "      evidence 파일명을 CONDITION 기반 run id로 남기며 k6를 실행한다."
	@echo "  make evidence-capture PHASE=02-no-lock-baseline K6_PRESET=baseline GRAFANA_PHASE=phase-02 SCENARIO=no-lock GRAFANA_PRESET=baseline CONDITION=baseline"
	@echo "      k6 evidence 실행 후 Grafana 캡처와 이미지 stitch를 수행한다."
	@echo "  make grafana-generate"
	@echo "      Grafana dashboard JSON을 생성한다."
	@echo "  make grafana-capture PHASE=02-no-lock-baseline GRAFANA_PHASE=phase-02 SCENARIO=no-lock GRAFANA_PRESET=baseline"
	@echo "      Grafana dashboard를 viewport part 이미지로 캡처한다."
	@echo "  make evidence-postprocess PHASE=02-no-lock-baseline"
	@echo "      Grafana part 이미지를 stitched-dashboard.png로 합친다."
	@echo "  make phase-status PHASE=02-no-lock-baseline"
	@echo "      phase 문서와 evidence 위치를 확인한다."
	@echo "  make k6-verify"
	@echo "      k6 reservation response expectation을 검증한다."
	@echo
	@echo "Compatibility targets:"
	@echo "  make phase3-grafana-capture STRATEGY=pessimistic-lock"
	@echo "  make phase3-grafana-captures"
	@echo "  make phase3-grafana-stitch STRATEGY=pessimistic-lock"
	@echo "  make phase3-grafana-stitches"
	@echo "  make phase3-sql-consistency STRATEGY=pessimistic-lock"
	@echo "  make phase3-sql-consistencies"
	@echo "  make phase4-sql-consistency EXPERIMENT=atomic-pool CONDITION=pool-10"
	@echo
	@echo "Common variables and defaults:"
	@echo "  PHASE=$(PHASE)"
	@echo "  GRAFANA_PHASE=$(GRAFANA_PHASE)"
	@echo "  SCENARIO=$(SCENARIO)"
	@echo "  PRESET=$(PRESET)"
	@echo "  K6_PRESET=$(K6_PRESET)"
	@echo "  GRAFANA_PRESET=$(GRAFANA_PRESET)"
	@echo "  MODE=$(MODE)"
	@echo "  POOL=$(POOL)"
	@echo "  POOL_SIZE=$(POOL_SIZE)"
	@echo "  LOCK_TIMEOUT=$(LOCK_TIMEOUT)"
	@echo "  PROFILE=$(PROFILE)"
	@echo "  PORT=$(PORT)"
	@echo "  CONDITION=$(CONDITION)"
	@echo "  TAIL=$(TAIL)"
	@echo "  PYTHON=$(PYTHON)"
	@echo "  DASHBOARD=$(DASHBOARD)"
	@echo "  RUN_WINDOW=$(RUN_WINDOW)"
	@echo "  STRATEGY=$(STRATEGY)"
	@echo "  PARTS_DIR=$(PARTS_DIR)"
	@echo "  SQL_OUTPUT=$(SQL_OUTPUT)"
