# postgresql.conf
listen_addresses = '*'

shared_preload_libraries = 'pg_stat_statements'  # 슬로우 쿼리 추적 활성화

pg_stat_statements.track = all                   # 모든 쿼리 추적
pg_stat_statements.max = 10000                   # 추적할 쿼리 수
track_activity_query_size = 2048                 # 쿼리 텍스트 저장 길이
